### ISSUE TITLE
selenium-webDriver does not exist

### ISSUE THREAD

**Issue by esaari** [browserstack/fast-selenium-scripts#5]
`require 'selenium-webDriver' if !defined?(Selenium::WebDriver)`

This requires an explicit require of `selenium-webdriver` before requiring `browserstack-fast-selenium` or the errant require statement runs and bails out.

Can you please fix the required gem name?

Sample log error: 
```
cannot load such file -- selenium-webDriver (LoadError)
/var/lib/jenkins-slave/workspace/jw7-commercial-canary-cucumber/test/cucumber/env/lib/ruby/gems/browserstack-fast-selenium-1.0.1/lib/browserstack-fast-selenium.rb:1:in `require'
/var/lib/jenkins-slave/workspace/jw7-commercial-canary-cucumber/test/cucumber/env/lib/ruby/gems/browserstack-fast-selenium-1.0.1/lib/browserstack-fast-selenium.rb:1:in `<top (required)>'
/var/lib/jenkins-slave/workspace/jw7-commercial-canary-cucumber/test/cucumber/features/support/env.rb:15:in `require'
/var/lib/jenkins-slave/workspace/jw7-commercial-canary-cucumber/test/cucumber/features/support/env.rb:15:in `block in <top (required)>'
/var/lib/jenkins-slave/workspace/jw7-commercial-canary-cucumber/test/cucumber/features/support/utilities/silencer.rb:5:in `suppress_warnings'
/var/lib/jenkins-slave/workspace/jw7-commercial-canary-cucumber/test/cucumber/features/support/env.rb:4:in `<top (required)>'
```

**Comment by francisf** [comment]
@esaari Thanks for raising this. We've merged the fix. Do try it out and let us know if you face any further issues.
